services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-saas-project
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

