apiVersion : v1
kind : Service 
metadata:
  name: devops-saas-service
  labels:
    app: devops-saas
spec:
  selector:
    app: devops-saas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

  